name: dave_al
description: "DAVE AI Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  android_alarm_manager_plus: ^4.0.4
  battery_plus: ^5.0.2
  flutter_tts: ^4.0.3
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
